version: "2"

formatters:
  enable:
    - gofmt
    - goimports
    - golines

linters:
  enable:
    - copyloopvar
    - err113
    - errorlint
    - exptostd
    - depguard
    - fatcontext
    - gocritic
    - govet
    - iface
    - importas
    - intrange
    - mirror
    - misspell
    - nakedret
    - nlreturn
    - nolintlint
    - perfsprint
    - protogetter
    - sloglint
    - staticcheck
    - tagalign
    - testifylint
    - usestdlibvars
    - usetesting
    - whitespace
    - wsl_v5
  settings:
    allow-first-in-block: true
    allow-whole-block: false
    branch-max-lines: 2
    depguard:
        main:
          allow:
            - $gostd
            - connectrpc.com/connect
            - connectrpc.com/cors
            - github.com/gin-contrib/cors
            - github.com/gin-contrib/sessions
            - github.com/gin-gonic/gin
            - github.com/gofrs/uuid/v5
            - github.com/joho/godotenv
