name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"
      - run: npm ci
      - run: npm run schema codegen
      - run: npm run backend codegen
      - run: npm run build
      - run: npm run lint
      - run: npm run test:coverage
